cloudprovider: custom

rancher:
  cattle:
    url: rancher.ranchers.io

cluster:
  annotations: {}
  labels: {}
  name: rke2-cluster-custom
  config:
    systemDefaultRegistry: docker.io
    kubernetesVersion: v1.26.10+rke2r2
    localClusterAuthEndpoint:
      enabled: false
    cni: canal
    docker: false
    disable_kube_proxy: false
    etcd_expose_metrics: false
    profile: cis-1.23
    selinux: true
    secrets_encryption: true
    write_kubeconfig_mode: 0600
    use_service_account_credentials: true
    protect_kernel_defaults: true
    kube_controller_manager_arg:
      - bind-address=127.0.0.1
      - use-service-account-credentials=true
      - tls-min-version=VersionTLS12
      - tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    kube_scheduler_arg:
      - tls-min-version=VersionTLS12
      - tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    kube_apiserver_arg:
      - tls-min-version=VersionTLS12
      - tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - authorization-mode=RBAC,Node
      - anonymous-auth=false
      - admission-control-config-file=/etc/rancher/rke2/rancher-pss.yaml
      - audit-policy-file=/etc/rancher/rke2/audit-policy.yaml
      - audit-log-mode=blocking-strict
      - audit-log-maxage=30
    kubelet_arg:
      - protect-kernel-defaults=true
      - read-only-port=0
      - authorization-mode=Webhook
      - streaming-connection-idle-timeout=5m
    registries:
      configs:
        rgcrprod.azurecr.us:
          authConfigSecretName: registryconfig-auth-97gjm
          caBundle: ''
          insecureSkipVerify: false
          tlsSecretName: ''
    upgradeStrategy:
      controlPlaneConcurrency: 10%
      controlPlaneDrainOptions:
        enabled: false
      workerConcurrency: 10%
      workerDrainOptions:
        enabled: false

addons:
  monitoring:
    enabled: true
    values:
      global:
        cattle:
          systemDefaultRegistry: rgcrprod.azurecr.us
  longhorn:
    enabled: true
    values:
      global:
        cattle:
          systemDefaultRegistry: rgcrprod.azurecr.us
  neuvector:
    enabled: true
    values:
      global:
        cattle:
          url: https://rancher.ranchers.io
          systemDefaultRegistry: rgcrprod.azurecr.us
      controller:
        ranchersso:
          enabled: true
      k3s:
        enabled: true
      manager:
        svc:
          type: ClusterIP
      rbac: true
